"""List the world's WorldPartitionHLOD actors and pick the one covering a target
point. READ-ONLY -- this chooses a build target, it does not build.

WHY A PROBE AND NOT A GUESS
    `-BuildSingleHLOD=<X>` matches `HLODActorDesc.GetActorLabel()` exactly
    (`WorldPartitionHLODsBuilder.cpp:1134`). The labels are generated by
    `-SetupHLODs` and are not predictable from the cell coordinates, so they
    have to be read.

WHY ACTOR DESCS AND NOT LEVEL ACTORS
    HLOD actors are spatially loaded World Partition actors; they are not in
    the editor's loaded set and `EditorActorSubsystem.get_all_level_actors()`
    will not show them. `UWorldPartitionBlueprintLibrary::GetActorDescs`
    (`WorldPartitionBlueprintLibrary.h:143-144`, BlueprintCallable) reads the
    DESCRIPTORS without loading the actors, and `FActorDesc` exposes
    `Label`, `Bounds`, `NativeClass` and `RuntimeGrid` as BlueprintReadOnly
    (:32-73).

THE TARGET
    Passed in as centimetres. For the mid_slope bench station the interesting
    content is not under the camera -- it is the 1-3 km band the camera looks
    into, which is where `mid_slope.png` measured 93.8% featureless. So the
    target is a point along the view ray, not the camera position.

Run via:
    python scripts/ue_exec.py scripts/payloads/hlod_pick_cell.py \
        --set TX=-241764 --set TY=293185
"""
import json as _json

import unreal as _u

TX = float("__TX__")
TY = float("__TY__")

_out = {"error": None, "target_cm": [TX, TY]}
try:
    _ues = _u.get_editor_subsystem(_u.UnrealEditorSubsystem)
    _w = _ues.get_editor_world()
    _out["level_path"] = _w.get_path_name()

    _r = _u.WorldPartitionBlueprintLibrary.get_actor_descs()
    # The binding may return the array, or (bool, array) for the out-param form.
    if isinstance(_r, tuple):
        _out["get_actor_descs_returned_tuple"] = True
        _descs = None
        for _item in _r:
            if isinstance(_item, (list, tuple)) or hasattr(_item, "__len__"):
                if not isinstance(_item, (str, bytes)):
                    _descs = _item
                    break
        if _descs is None:
            _descs = []
    else:
        _out["get_actor_descs_returned_tuple"] = False
        _descs = _r
    _out["desc_total"] = len(_descs)

    _hlods = []
    _classes = {}
    for _d in _descs:
        try:
            _nc = _d.get_editor_property("native_class")
            _cn = _nc.get_name() if _nc else "None"
        except Exception:
            _cn = "<unreadable>"
        _classes[_cn] = _classes.get(_cn, 0) + 1
        if _cn != "WorldPartitionHLOD":
            continue
        try:
            _b = _d.get_editor_property("bounds")
            _mn, _mx = _b.min, _b.max
            _cx = (_mn.x + _mx.x) * 0.5
            _cy = (_mn.y + _mx.y) * 0.5
            _cz = (_mn.z + _mx.z) * 0.5
            _inside = (_mn.x <= TX <= _mx.x) and (_mn.y <= TY <= _mx.y)
            _hlods.append({
                "label": str(_d.get_editor_property("label")),
                "name": str(_d.get_editor_property("name")),
                "runtime_grid": str(_d.get_editor_property("runtime_grid")),
                "centre_cm": [round(_cx, 1), round(_cy, 1), round(_cz, 1)],
                "extent_cm": [round(_mx.x - _mn.x, 1), round(_mx.y - _mn.y, 1),
                              round(_mx.z - _mn.z, 1)],
                "dist_to_target_cm": round(
                    ((_cx - TX) ** 2 + (_cy - TY) ** 2) ** 0.5, 1),
                "contains_target_xy": bool(_inside),
                "package": str(_d.get_editor_property("actor_package")),
            })
        except Exception as _e:
            _hlods.append({"error": type(_e).__name__ + ": " + str(_e)})

    _out["class_histogram"] = dict(sorted(_classes.items()))
    _out["hlod_count"] = len(_hlods)
    _ok = [_h for _h in _hlods if "dist_to_target_cm" in _h]
    _ok.sort(key=lambda _h: _h["dist_to_target_cm"])
    _out["containing_target"] = [_h for _h in _ok if _h["contains_target_xy"]]
    _out["nearest_8"] = _ok[:8]
    _out["runtime_grids_seen"] = sorted(
        set(_h.get("runtime_grid", "") for _h in _ok))
    del _w
except Exception as _e:
    import traceback as _tb
    _out["error"] = type(_e).__name__ + ": " + str(_e)
    _out["trace"] = _tb.format_exc()[-1500:]

print("__LL__" + _json.dumps(_out))
