"""current_values.py -- generate RECIPES.md's CURRENT VALUES table, and prove
it against its sources (closure D-1 item 6, PASS4 plan section 3).

    python scripts/current_values.py            # print the table
    python scripts/current_values.py --write     # write it into RECIPES.md
    python scripts/current_values.py --selftest   # every JSON-backed row == source

WHY A GENERATED TABLE. The in-force numbers were scattered across LESSONS,
RECIPES prose, STATE and the registers, and superseded values were being
read as current. This table is ONE screen of what is in force now, its
ruling id, its read-back artefact, and its doc basis -- and every row that
maps to a recipe/benchmark field is REGENERATED from that field, so it
cannot drift. Ruling-only rows (judgement camera, dead cvars, HLOD policy)
carry no JSON source and are marked so.

THE BASELINE RULE (added 2026-09-15): no capture before 2026-09-15 Block A
is a baseline. The A-6 certified capture (target_a6_joint2: card R/G
1.0014, B/G 0.998) is the ZERO for every comparison from here -- earlier
frames predate the joint WB solve, the D6000 shade floor, the sky-colour
fix and the uniform-4096 world, and differ from now by far more than any
signal under test (B-5 measured a 09-13->now frame diff of mean 0.083).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RECIPE = os.path.join(REPO, "recipes", "alpine_8k.json")
BENCH = os.path.join(REPO, "research", "audit", "inputs", "benchmark.json")

BEGIN = "<!-- CURRENT_VALUES:BEGIN -- generated by scripts/current_values.py -->"
END = "<!-- CURRENT_VALUES:END -->"


def _load(path):
    with open(path, encoding="utf-8-sig") as fh:
        return json.load(fh)


def _dig(obj, path):
    # path is a list of keys, or a dotted string (split on "."). A list is
    # required when a key CONTAINS a dot, e.g. benchmark's
    # "mrq.temporal_samples".
    cur = obj
    for k in (path if isinstance(path, list) else path.split(".")):
        cur = cur[k]
    return cur


# Each row: (value, in_force, ruling, read_back, basis, verify)
# verify is None (ruling-only) or (source_file, dotted_path, transform, needle)
# -- the selftest asserts str(transform(source_value)) == needle AND needle in
# in_force, so the printed value and the live source cannot disagree.
def _rows():
    R, B = "recipe", "bench"
    return [
        ("judgement camera", "3840x2160 @ 90 deg H; 1440p floor", "standing",
         "benchmark declared_camera", "Ruling",
         (B, "declared_camera.fov_h_deg", lambda v: "%g" % v, "90")),
        ("loading range", "512 m", "R-RANGE", "apply_streaming_range read-back",
         "Project", (R, "streaming.main_loading_range_cm",
                     lambda v: "%g" % (v / 100.0), "512")),
        ("metering", "Manual, physical camera exposure off", "R-METER",
         "PPV read-back", "Doc (Manual = fixed exposure)",
         (R, "lighting.exposure.method", str, "manual")),
        ("compensation_ev", "-14.2571", "A-6 R-WB2x2", "PPI0 card 0.1805",
         "Project", (R, "lighting.exposure.compensation_ev",
                     lambda v: "%g" % v, "-14.2571")),
        ("render warm-up", "40 frames ON; engine warm-up 300", "R-METER",
         "sidecar", "Doc (engine warm-up renders nothing; render warm-up "
         "builds history)", (B, "residency.engine_warm_up_frames",
                             lambda v: "%g" % v, "300")),
        ("temporal samples (target)", "8", "R-BENCHCAPTURE",
         "cvars_match per job", "Doc",
         (B, ["profiles", "target", "mrq.temporal_samples"],
          lambda v: "%g" % v, "8")),
        ("white_temp_k", "3438.6", "A-6 R-WB2x2", "card R/G 1.0014",
         "Doc (WB mode) + Project",
         (R, "lighting.grade.white_temp_k", lambda v: "%g" % v, "3438.6")),
        ("white_tint", "-0.0248", "A-6 R-WB2x2", "card B/G 0.998",
         "Doc (tint axis) + Project",
         (R, "lighting.grade.white_tint", lambda v: "%g" % v, "-0.0248")),
        ("contrast", "0.95 effective (w; xyz=1)", "B3.13", "product read-back",
         "Project (shader xyz.w)",
         (R, "lighting.grade.contrast", lambda v: "%g" % v, "0.95")),
        ("sun", "130000 lux, 5200 K, 12 deg / 285 deg", "Brief 2",
         "8/8 read-backs (A-4)", "Doc (lux, use_temperature)",
         (R, "lighting.sun.intensity_lux", lambda v: "%g" % v, "130000")),
        ("fog", "density 0.00416, start 0, half-height 517.49 m, "
         "inscattering black", "Brief 2", "fog_state",
         "Doc (Sky Atmosphere colours the fog)",
         (R, "lighting.fog.density", lambda v: "%g" % v, "0.00416")),
        ("shade band", "2.065-2.998 @ 3438.6 K, floor D6000 (sun < 30 deg)",
         "R-SHADEBAND", "shade_reference.py", "Ruling + literature", None),
        ("sky light", "white (1,1,1), 1.0, real-time capture, lower "
         "hemisphere black", "R-SKYCOLOR, Brief 2", "FColor 255,255,255",
         "Doc + census", None),
        ("instruments", "ppi0 / finalimage_linear / finalimage_look / truth "
         "(20 GO props)", "R-INSTRUMENTS, S-12", "sidecar instrument field",
         "Doc (Disable Tone Curve = pipeline linear)", None),
        ("look-instrument format", "EXR 16-bit float; PNG viewing only", "S-4",
         "config dump (A-5)", "Doc (EXR output class)", None),
        ("tiling verdict instrument", "player (temporal 8, TSR)", "B3.20",
         "TASK3_RECORD", "Doc (TSR removes moire)", None),
        ("landscape HLOD", "HLODTextureSize 4096 (0.49 m/texel), SPECIFIC_SIZE, "
         "257/257; was 1024 (2 m/texel), NOT 256; layers _Landscape/"
         "_FoliageApprox inert", "R-HLODTEX, B3.21, S-8b",
         "off-disk + live census (B-6)", "Project (ULandscapeHLODBuilder "
         "unconditional)", None),
        ("perf budget", "GPU 1.2x standalone p90/zone; game 6.0 ms; frame "
         "16.6 ms; ABSOLUTE, 4096 passes", "R-PERFBUDGET", "9a561d07", "Ruling",
         None),
        ("dead cvars", "r.LandscapeLODBias, r.TonemapperFilm, r.ExpandGamut, "
         "r.LocalExposure.*, r.Shadow.Virtual.Nanite.Enable, landscape."
         "ForcedLOD, r.Wind.Enable, foliage.WindEnabled", "P1-4/5",
         "cvars_5_8_live.txt", "Live", None),
    ]


def verify_rows(rows=None):
    """Return (ok, failures). Each JSON-backed row's live source value must
    match the needle that also appears in the printed in_force string."""
    recipe, bench = _load(RECIPE), _load(BENCH)
    src = {"recipe": recipe, "bench": bench}
    failures = []
    for value, in_force, _r, _rb, _b, verify in (rows if rows is not None
                                                 else _rows()):
        if verify is None:
            continue
        sf, path, xf, needle = verify
        try:
            live = xf(_dig(src[sf], path))
        except Exception as e:  # noqa
            failures.append("%s: source read failed (%s.%s): %s"
                            % (value, sf, path, e))
            continue
        if live != needle:
            failures.append("%s: source %s.%s = %r but table says %r"
                            % (value, sf, path, live, needle))
        elif needle.lower() not in in_force.lower():
            failures.append("%s: needle %r not in the in-force text %r"
                            % (value, needle, in_force))
    return (not failures), failures


def table_md():
    lines = [BEGIN,
             "# CURRENT VALUES -- the in-force spec, generated (do not hand-edit)",
             "",
             "**Generated by `scripts/current_values.py` from "
             "`recipes/alpine_8k.json` + `benchmark.json`. Selftest asserts "
             "every JSON-backed row equals its source; ruling-only rows carry "
             "no source and say so.** Regenerate with "
             "`python scripts/current_values.py --write`.",
             "",
             "⭐ **BASELINE RULE:** no capture before 2026-09-15 Block A is a "
             "baseline. The **A-6 certified capture** (card R/G 1.0014, B/G "
             "0.998) is the ZERO for every comparison from here; earlier "
             "frames predate the joint WB solve, the D6000 shade floor, "
             "R-SKYCOLOR and the uniform-4096 world.",
             "",
             "| value | in force | ruling | read-back | basis | source |",
             "|---|---|---|---|---|---|"]
    for value, in_force, ruling, rb, basis, verify in _rows():
        source = ("%s `%s`" % verify[:2][::-1]) if verify else "ruling (no JSON)"
        lines.append("| %s | %s | %s | %s | %s | %s |"
                     % (value, in_force, ruling, rb, basis, source))
    lines.append(END)
    return "\n".join(lines)


def write_into_recipes():
    path = os.path.join(REPO, "RECIPES.md")
    with open(path, encoding="utf-8") as fh:
        body = fh.read()
    block = table_md()
    if BEGIN in body and END in body:
        body = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block,
                      body, count=1, flags=re.DOTALL)
    else:
        # Insert as the FIRST section, right after the H1 title line.
        nl = body.index("\n")
        body = body[:nl + 1] + "\n" + block + "\n" + body[nl + 1:]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body)
    return path


def selftest():
    ok, failures = verify_rows()
    n = sum(1 for r in _rows() if r[5] is not None)
    print("  %d JSON-backed rows checked against source" % n)
    for f in failures:
        print("  FAIL:", f)
    # FAIL DIRECTION: a source that disagrees with the table MUST be caught,
    # or the check is decorative. Corrupt one row's needle and confirm
    # verify_rows refuses.
    bad = list(_rows())
    v = bad[3][5]                            # compensation_ev's verify tuple
    bad[3] = bad[3][:5] + ((v[0], v[1], v[2], "-99.9"),)
    caught = not verify_rows(bad)[0]
    print("  fail-direction (wrong needle refused): %s" % ("PASS" if caught
                                                           else "FAIL"))
    ok = ok and caught
    print("selftest %s" % ("OK" if ok else "FAILED"))
    return 0 if ok else 1


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args(argv)
    if a.selftest:
        return selftest()
    if a.write:
        ok, failures = verify_rows()
        if not ok:
            print("REFUSE: not writing -- rows disagree with source:")
            for f in failures:
                print("  ", f)
            return 1
        p = write_into_recipes()
        print("wrote CURRENT VALUES into", os.path.relpath(p, REPO))
        return 0
    print(table_md())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
