# disk_cleanup_20260927.ps1 -- Ryan-authorised deletion of regenerable caches
# and scratch (2026-09-27, "yes delete all of those"). Standing rule 2 forbids
# recursive/forced deletes from the agent and the hook enforces it, so this
# runs from the operator's prompt:   ! powershell -File scripts/disk_cleanup_20260927.ps1
# Everything here is regenerated by the editor (DDC, Intermediate,
# ShaderDebugInfo, Autosaves, Profiling), already copied under research/
# (Screenshots), older than today (Logs) or older than 2026-09-20 (_trash).
# Refuses if an editor is running.
$ErrorActionPreference = "Continue"
Set-Location (Split-Path -Parent $PSScriptRoot)
if (Get-Process UnrealEditor -ErrorAction SilentlyContinue) { Write-Output "REFUSE: editor running"; exit 1 }
$before = (Get-PSDrive C).Free/1GB
$targets = @("LandscapeLab\Saved\ShaderDebugInfo", "LandscapeLab\Saved\Autosaves",
             "LandscapeLab\Saved\Profiling", "LandscapeLab\Saved\Screenshots",
             "LandscapeLab\Intermediate", "LandscapeLab\DerivedDataCache")
foreach ($t in $targets) {
    if (Test-Path $t) {
        $gb = [math]::Round((Get-ChildItem $t -Recurse -File -ErrorAction SilentlyContinue | Measure-Object Length -Sum).Sum/1GB, 2)
        Remove-Item $t -Recurse -Force -Confirm:$false -ErrorAction SilentlyContinue
        Write-Output "deleted $t ($gb GB)"
    }
}
$logs = Get-ChildItem "LandscapeLab\Saved\Logs" -File -ErrorAction SilentlyContinue | Where-Object { $_.LastWriteTime -lt (Get-Date).Date }
$lgb = [math]::Round(($logs | Measure-Object Length -Sum).Sum/1GB, 2)
$logs | Remove-Item -Force -Confirm:$false -ErrorAction SilentlyContinue
Write-Output "deleted $($logs.Count) log files older than today ($lgb GB)"
$old = Get-ChildItem "_trash" -Directory -ErrorAction SilentlyContinue | Where-Object { $_.LastWriteTime -lt [datetime]"2026-09-20" }
foreach ($d in $old) {
    $gb = [math]::Round((Get-ChildItem $d.FullName -Recurse -File -ErrorAction SilentlyContinue | Measure-Object Length -Sum).Sum/1GB, 2)
    Remove-Item $d.FullName -Recurse -Force -Confirm:$false -ErrorAction SilentlyContinue
    Write-Output "deleted _trash\$($d.Name) ($gb GB)"
}
$after = (Get-PSDrive C).Free/1GB
Write-Output ("free before {0:N1} GB -> after {1:N1} GB" -f $before, $after)
