"""Generate the greppable TOC at the top of LESSONS.md and RECIPES.md.

WHY THIS EXISTS
---------------
LESSONS.md is 1.37 MB and RECIPES.md is 688 KB. Both are APPEND-ONLY LAW and
may never be trimmed, so the only way to make them navigable is an index at the
top. A session greps the TOC, then jumps to the one entry it needs, instead of
pulling a megabyte into context.

WHAT IT MAY AND MAY NOT DO
--------------------------
It may ONLY insert or replace a block between the TOC markers. On every WRITE
run it re-reads the file afterward and asserts the body below the marker is
still byte-identical to what it was (a post-write sanity check, not a
pre-write veto) -- because this script edits two files the project's standing
rules forbid deleting from, and "the generator trimmed it" is exactly the
accident that rule guards against. (--check writes nothing and skips it.)

[historic] TAGGING is deliberately CONSERVATIVE. An entry is marked historic
only when it names a pre-8K subject AND never mentions the 8K world. When in
doubt it is left unmarked -- mislabelling live doctrine as historic is the
expensive error, the same rule the consolidation inventory runs on.

Usage:  python scripts/gen_doc_tocs.py [--check]
        --check exits 3 if a TOC is missing or stale, and writes nothing.
"""
import io
import os
import re
import sys

# ASCII-SAFE STDOUT -- see check_docs.py.
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BEGIN = "<!-- TOC:BEGIN — generated by scripts/gen_doc_tocs.py — DO NOT EDIT BY HAND -->"
END = "<!-- TOC:END -->"

# Keyword -> tag. First match wins per tag; an entry may carry several.
TAGS = [
    ("terrain", r"terrain|heightmap|stamp|erosion|gaea|landscape|nanite|displac"),
    ("material", r"material|sampler|texture|triplanar|shader|weightmap|ORM"),
    ("foliage", r"foliage|tree|conifer|spruce|grass|scatter|instance|understory"),
    ("rock", r"rock|boulder|talus|cliff|scree"),
    ("city", r"city|town|street|building|plaza|kit|medieval|modular"),
    ("encounter", r"encounter|marker|director|POI"),
    ("nav", r"navmesh|navigation|recast|reachab|walkab|agent"),
    ("hero", r"hero|metahuman|groom|hair|beard|face|DNA|blender|skeleton|anim"),
    ("render", r"render|capture|screenshot|frame|camera|exposure|sweep|HighResShot"),
    ("editor", r"editor|crash|wedge|modal|restore|autosave|remote exec|MCP|plugin"),
    ("api", r"API|reflect|stub|UFUNCTION|python|accessor|signature"),
    ("gate", r"gate|verify|verific|refus|assert|control|prove|check|measur"),
    ("asset", r"asset|licence|license|intake|fab|megascan|import|vendor"),
    ("perf", r"GPU|ms\b|memory|RAM|budget|cost|throttl|residen"),
]

# Pre-8K subject markers, and the 8K markers that immunise an entry.
PRE8K = re.compile(r"/Game/Alpine(?![8A-Za-z0-9])|alpine_heightmap|2017|"
                   r"AlpineLab_v1|Pass [0-7]\b|fir_tree_01", re.I)
IS8K = re.compile(r"Alpine8K|8129|alpine_8k", re.I)


def tags_for(text):
    out = []
    low = text
    for name, pat in TAGS:
        if re.search(pat, low, re.I):
            out.append(name)
    return out[:4]


def entries_recipes(text):
    """Recipe entries: h1/h2/h3 whose title starts with an R-id."""
    pat = re.compile(r"^(#{1,3}) ((?:R\d+|R-[A-Z0-9]+(?:-[A-Z0-9]+)*)\b.*)$", re.M)
    out = []
    for m in pat.finditer(text):
        title = m.group(2).strip()
        rid = re.match(r"(R\d+|R-[A-Z0-9-]+)", title).group(1)
        line = text.count("\n", 0, m.start()) + 1
        out.append((rid, title, line, m.start()))
    return out


def entries_lessons(text):
    """Lesson entries: dated h2s, plus divisions/sessions (h1) and numbered h2s."""
    pat = re.compile(r"^(#{1,2}) (.+)$", re.M)
    out = []
    for m in pat.finditer(text):
        title = m.group(2).strip()
        if title.startswith("TOC") or title.startswith("<!--"):
            continue
        line = text.count("\n", 0, m.start()) + 1
        dm = re.match(r"(\d{4}-\d{2}-\d{2}[a-z]?)", title)
        key = dm.group(1) if dm else ("§" if m.group(1) == "##" else "DIV")
        out.append((key, title, line, m.start()))
    return out


STATUS_RE = re.compile(r"^> STATUS:\s*([A-Z][A-Z-]*)", re.M)


def status_for(body):
    """The STATUS tag on the `> STATUS:` line DIRECTLY under an entry's own
    heading (closure D-1 item 5), or '-' if the entry carries none. Only the
    lines immediately after the heading count -- a STATUS line deeper in the
    body belongs to a SUB-heading (e.g. a `### REJECTED` block inside an
    R-entry) and must NOT leak up to the parent, or a current recipe reads
    as superseded because one of its rejected sub-parts is tagged."""
    lines = body.split("\n")
    # lines[0] is the heading; scan only the next few until real content.
    for ln in lines[1:4]:
        s = ln.strip()
        if s.startswith("> STATUS:"):
            m = STATUS_RE.match(s)
            return m.group(1) if m else "-"
        if s and not s.startswith(">"):
            break        # hit body content before a STATUS line
    return "-"


def build_toc(text, kind, entries):
    rows = []
    for i, (key, title, line, off) in enumerate(entries):
        nxt = entries[i + 1][3] if i + 1 < len(entries) else len(text)
        body = text[off:nxt]
        status = status_for(body)
        # HISTORIC IS JUDGED ON THE TITLE, NOT THE BODY -- and this was a real
        # defect on the first run. Matching the body marked R0 (fresh-machine
        # foundation), R2 (landscape material), R4 (foliage placement), R6
        # (lighting/capture/save) and R8 (crash recovery) as historic, because
        # every one of them MENTIONS the pre-8K world it was developed against.
        # All five are live procedure. A recipe is historic when its SUBJECT is
        # superseded, not when its prose recalls where it was written.
        hist = " `[historic]`" if (PRE8K.search(title) and not IS8K.search(title)) else ""
        tg = ",".join(tags_for(title + " " + body[:1500]))
        t = title if len(title) <= 78 else title[:75] + "..."
        t = t.replace("|", "\\|")
        rows.append("| `%s` | %s | %s | %s |%s"
                    % (key, t, status, tg, hist and (" " + hist) or " "))
    head = (
        "%s\n\n"
        "## TOC — %d entries. **Grep THIS, not the body.**\n\n"
        "*Generated by `scripts/gen_doc_tocs.py`. The body below is append-only law\n"
        "and is never touched by the generator — only this block is rewritten.*\n"
        "**`[historic]`** marks an entry whose subject is the pre-8K world and which\n"
        "never mentions the 8K one. The **status** column reads the `> STATUS:`\n"
        "line under each heading (CURRENT / SUPERSEDED-BY / HISTORY / WRONG; `-` if\n"
        "none) so a grep on the TOC shows the state before the body is read.\n\n"
        "| id/date | entry | status | tags | |\n|---|---|---|---|---|\n"
    ) % (BEGIN, len(entries))
    return head + "\n".join(rows) + "\n\n" + END + "\n"


def process(path, kind, check):
    full = os.path.join(REPO, path)
    text = io.open(full, encoding="utf-8", newline="").read()

    # IDEMPOTENCE: the separator newlines between the TOC and the body live in
    # exactly one place, and the body is always stored WITHOUT leading
    # newlines. The first version of this appended one newline per run, so the
    # file grew forever and --check reported STALE on a freshly generated file
    # -- which would have left the offline suite permanently red. Caught by
    # hashing three consecutive runs, not by reasoning about it.
    #
    # Nothing is deleted: any newlines that originally followed the title are
    # kept, in the PREFIX, ahead of the TOC.
    if BEGIN in text:
        a = text.index(BEGIN)
        b = text.index(END) + len(END)
        prefix, body = text[:a], text[b:].lstrip("\n")
    else:
        nl = text.index("\n") + 1
        rest = text[nl:]
        lead = len(rest) - len(rest.lstrip("\n"))
        prefix, body = text[:nl] + rest[:lead], rest[lead:]

    entries = (entries_recipes if kind == "recipes" else entries_lessons)(body)
    toc = build_toc(body, kind, entries)
    new = prefix + toc + "\n" + body

    if check:
        stale = (BEGIN not in text) or (new != text)
        print("%-14s %s  (%d entries)" % (path, "STALE" if stale else "ok", len(entries)))
        return 3 if stale else 0

    io.open(full, "w", encoding="utf-8", newline="").write(new)

    # POST-WRITE SANITY CHECK: re-read and confirm the file on disk still ENDS
    # with the original body byte-for-byte, i.e. the rewrite touched only the
    # TOC block above it and did not truncate or mangle the append-only law
    # below. NOTE: the write has already happened above, so this does not
    # "prevent" a bad state -- it catches one after the fact and aborts loudly.
    after = io.open(full, encoding="utf-8", newline="").read()
    assert after.endswith(body), \
        "BODY MISMATCH AFTER WRITE — %s no longer ends with the original " \
        "body; investigate before anything else touches it" % path
    # Count historic TABLE ROWS only ("| ..."), not the legend line in the
    # header (which also contains the literal "[historic]").
    n_hist = sum(1 for ln in toc.splitlines()
                 if ln.startswith("|") and "[historic]" in ln)
    print("%-14s TOC written: %d entries, %d historic, TOC %d chars, body %d chars"
          % (path, len(entries), n_hist, len(toc), len(body)))
    return 0


def main():
    check = "--check" in sys.argv
    rc = 0
    rc |= process("RECIPES.md", "recipes", check)
    rc |= process("LESSONS.md", "lessons", check)
    return rc


if __name__ == "__main__":
    sys.exit(main())
