"""Take the HLOD build's derived packages out of git, and PROVE both directions.

WHY THIS EXISTS
    `-BuildHLODs` inflates ~2,267 packages under
    `LandscapeLab/Content/__ExternalActors__/` from ~130-byte stubs to MB-scale
    meshes with baked textures -- on the order of 15-20 GB. That content is
    DERIVED: a commandlet regenerates it from the source actors and the HLOD
    layers. `LandscapeLab/Content` is tracked, in a 41 GB repository that
    already carries unresolved history bloat.

    It cannot be excluded by a path pattern. World Partition hash-buckets HLOD
    actor packages into the SAME GUID-named directories as the real actors
    (`__ExternalActors__/Alpine8K/9/Y9/ZICA05QVUQWNSNFHZ63GBX.uasset` is an
    HLOD; its neighbours are landscape proxies and foliage). Nothing in the
    path distinguishes them, so the set must be enumerated.

THE THING THAT MAKES THIS NOT A GITIGNORE PROBLEM
    **The packages are already TRACKED.** `-SetupHLODs` created them as stubs
    and those stubs were committed on 2026-09-08. `.gitignore` DOES NOT APPLY
    TO TRACKED PATHS -- adding them would be a silent no-op that reads as
    success, and the 15-20 GB would sail into the next commit anyway. Measured
    while the build was still running: 0 untracked, 94 tracked-and-rewritten.

    So the operation is `git rm --cached` (drop from the index, keep on disk)
    AND the ignore entry. Because the inflated content has never been
    committed, doing this BEFORE any commit means **no bloat enters history at
    all** -- what history holds is the ~130-byte stubs, which are negligible.

IDENTIFICATION IS BY CONTENT SIGNATURE, NOT BY PATH OR MTIME (standing rule 8)
    `git rm --cached` on a real actor would be a genuine defect, so membership
    is not inferred from the directory or the timestamp. A package is an HLOD
    package iff the bytes contain the class name `WorldPartitionHLOD`.
    Verified 2026-09-08: a built HLOD package hits 3-7 times, a
    `LandscapeStreamingProxy` package hits 0. The signature appears within the
    first 16 KB (checked on the 13.9 MB cell), so the scan reads a 1 MB head
    and only falls back to a full read when the head is inconclusive.

    Membership is gated by TWO conditions: the file is under
    `__ExternalActors__` (the walk root) AND carries the class signature.
    mtime newer than the build-start marker is REPORTED (the pre_marker count)
    but does NOT gate membership -- see the note at the walk below.

THE MARKER
    Written immediately before the commandlet launches. Comparing file mtimes
    against another file's mtime needs no parsing and no time-zone reasoning.

VERIFICATION IS BOTH DIRECTIONS, and it is the point of the script
    POSITIVE: manifest packages are ignored, and absent from `git ls-files`.
    NEGATIVE: the HLOD layer ASSETS, `Alpine8K.umap`, the manifest itself and a
              sample of ordinary tracked actors are NOT ignored and REMAIN
              tracked.
    A one-directional check passes just as happily with `*` in `.gitignore`.

Run: python scripts/hlod_gitignore.py            # dry run, writes nothing
     python scripts/hlod_gitignore.py --apply    # manifest + .gitignore + untrack
"""
from __future__ import annotations

import argparse
import io
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# SCOPED TO ONE WORLD, DELIBERATELY.
# Membership is the WorldPartitionHLOD signature, and dropping the mtime gate
# (needed to catch cells built before this run's marker) made the scan reach
# HLOD packages belonging to OTHER worlds -- `/Game/Alpine` the pre-8K world,
# Canyon, ForgeWorld and the rest. Those are equally derived in principle, but
# nothing in this repo documents how to rebuild them, and untracking them would
# empty them out of a fresh clone with no recipe to restore them. Out of scope:
# this tool untracks the HLOD of the world it was pointed at.
WORLD = "Alpine8K"
EXT_ACTORS = "LandscapeLab/Content/__ExternalActors__/" + WORLD
MARKER = "_verify/hlod/20260908/BUILD_START_MARKER"
MANIFEST = "_verify/hlod/hlod_packages.txt"
GITIGNORE = ".gitignore"
SIGNATURE = b"WorldPartitionHLOD"
HEAD_BYTES = 1 << 20

BEGIN = "# >>> HLOD derived content -- generated by scripts/hlod_gitignore.py >>>"
END = "# <<< HLOD derived content <<<"

CONTROLS_MUST_STAY_TRACKED = [
    "LandscapeLab/Content/Alpine8K.umap",
    "LandscapeLab/Content/Alpine8K_HLODLayer_Instanced.uasset",
    "LandscapeLab/Content/Alpine8K_HLODLayer_Merged.uasset",
    "LandscapeLab/Content/Alpine8K_HLODLayer_Landscape.uasset",
    "LandscapeLab/Content/Alpine8K_HLODLayer_FoliageApprox.uasset",
]


def git(*args: str) -> str:
    return subprocess.run(["git"] + list(args), cwd=REPO, check=True,
                          capture_output=True, text=True).stdout


def check_ignored(path: str) -> bool:
    r = subprocess.run(["git", "check-ignore", "-q", "--no-index", path],
                       cwd=REPO, capture_output=True)
    return r.returncode == 0


def is_hlod(full: str, size: int) -> bool:
    """Content signature. Head-first, full read only when inconclusive."""
    with io.open(full, "rb") as fh:
        head = fh.read(HEAD_BYTES)
        if SIGNATURE in head:
            return True
        if size <= HEAD_BYTES:
            return False          # head WAS the whole file: definitive
        while True:
            chunk = fh.read(HEAD_BYTES)
            if not chunk:
                return False
            if SIGNATURE in chunk:
                return True


def human(n: float) -> str:
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1024 or unit == "TB":
            return "%.1f %s" % (n, unit)
        n /= 1024.0
    return str(n)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true",
                    help="write the manifest, the .gitignore block, and "
                         "git rm --cached the tracked HLOD packages")
    a = ap.parse_args()

    marker = os.path.join(REPO, MARKER)
    if not os.path.isfile(marker):
        print("REFUSE: no build start marker at " + MARKER)
        print("        Without it this build's output cannot be told from")
        print("        packages that were already on disk.")
        return 2
    cutoff = os.stat(marker).st_mtime
    print("marker       %s" % MARKER)

    root = os.path.join(REPO, EXT_ACTORS)
    if not os.path.isdir(root):
        print("REFUSE: no such directory: " + EXT_ACTORS)
        return 2

    tracked = set()
    for line in git("ls-files", "--", EXT_ACTORS).splitlines():
        if line.strip():
            tracked.add(line.strip())
    print("tracked      %d packages under %s" % (len(tracked), EXT_ACTORS))

    # THE SIGNATURE IS THE TEST; THE MARKER ONLY DATES THINGS.
    # An earlier version required mtime > marker, which is the right rule for
    # "what did THIS build produce" and the WRONG rule for "what must not be in
    # git". It missed the 6 cells built on 2026-09-08 before the full run --
    # already tracked, already carrying real geometry. Left tracked they would
    # show as modified after every future rebuild and be recommitted each time,
    # accumulating exactly the bloat this script exists to prevent. So
    # membership is the SIGNATURE, and the marker is kept for reporting how
    # much of the set this particular build wrote.
    hlod_tracked, hlod_untracked, skipped_not_hlod = [], [], 0
    total = 0
    pre_marker = 0
    stat_errors = 0
    for dirpath, _dirs, files in os.walk(root):
        for fn in files:
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, REPO).replace(os.sep, "/")
            try:
                st = os.stat(full)
            except OSError:
                stat_errors += 1     # record, don't silently drop the file
                continue
            try:
                if not is_hlod(full, st.st_size):
                    skipped_not_hlod += 1
                    continue
            except OSError:
                skipped_not_hlod += 1
                continue
            if st.st_mtime <= cutoff:
                pre_marker += 1
            total += st.st_size
            (hlod_tracked if rel in tracked else hlod_untracked).append(rel)

    derived = sorted(hlod_tracked + hlod_untracked)
    print("HLOD         %d packages by signature, %s"
          % (len(derived), human(total)))
    print("               of which %d predate the build marker (earlier runs)"
          % pre_marker)
    print("               tracked   %d  -> need git rm --cached"
          % len(hlod_tracked))
    print("               untracked %d  -> .gitignore alone suffices"
          % len(hlod_untracked))
    print("skipped      %d non-HLOD files (no class signature, or unreadable "
          "head) -- left completely alone" % skipped_not_hlod)
    if stat_errors:
        print("stat errors  %d files could not be stat'd and were dropped "
              "from every tally" % stat_errors)

    if not derived:
        print("nothing to do")
        return 0

    if not a.apply:
        print("")
        print("DRY RUN -- nothing written. Re-run with --apply.")
        print("sample: " + derived[0])
        return 0

    # ---- manifest --------------------------------------------------------
    man = os.path.join(REPO, MANIFEST)
    os.makedirs(os.path.dirname(man), exist_ok=True)
    with io.open(man, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# HLOD build products -- generated by scripts/hlod_gitignore.py\n")
        fh.write("# %d packages, %s. DERIVED: regenerate, never restore.\n"
                 % (len(derived), human(total)))
        fh.write("#   UnrealEditor-Cmd <proj> /Game/Alpine8K \\\n")
        fh.write("#     -run=WorldPartitionBuilderCommandlet \\\n")
        fh.write("#     -Builder=WorldPartitionHLODsBuilder -BuildHLODs \\\n")
        fh.write("#     -noxgecontroller -AllowCommandletRendering\n")
        fh.write("# Identified by the WorldPartitionHLOD class signature in the\n")
        fh.write("# package bytes, not by path -- HLOD and real actors share\n")
        fh.write("# the same hash-bucketed directories.\n")
        for rel in derived:
            fh.write(rel + "\n")
    print("manifest     %s" % MANIFEST)

    # ---- untrack, in batches (2,267 paths overflow a command line) --------
    if hlod_tracked:
        B = 200
        for i in range(0, len(hlod_tracked), B):
            git("rm", "--cached", "--quiet", "--", *hlod_tracked[i:i + B])
        print("untracked    git rm --cached on %d packages (files kept on disk)"
              % len(hlod_tracked))

    # ---- .gitignore, generated block replaced in place --------------------
    gi = os.path.join(REPO, GITIGNORE)
    old = []
    if os.path.isfile(gi):
        with io.open(gi, encoding="utf-8") as fh:
            old = fh.read().split("\n")
    kept, skipping = [], False
    for line in old:
        if line.strip() == BEGIN:
            skipping = True
            continue
        if line.strip() == END:
            skipping = False
            continue
        if not skipping:
            kept.append(line)
    while kept and kept[-1].strip() == "":
        kept.pop()

    with io.open(gi, "w", encoding="utf-8", newline="\n") as fh:
        for line in kept:
            fh.write(line + "\n")
        fh.write("\n" + BEGIN + "\n")
        fh.write("# %d derived HLOD packages, %s. Regenerate, never restore\n"
                 % (len(derived), human(total)))
        fh.write("# from a backup. Full list: " + MANIFEST + "\n")
        fh.write("# Leading slash anchors each to the repo root.\n")
        for rel in derived:
            fh.write("/" + rel + "\n")
        fh.write(END + "\n")
    print("gitignore    %s  (+%d entries)" % (GITIGNORE, len(derived)))

    # ---- VERIFY BOTH DIRECTIONS ------------------------------------------
    print("")
    print("VERIFY")
    fails = []

    now_tracked = set()
    for line in git("ls-files", "--", EXT_ACTORS).splitlines():
        if line.strip():
            now_tracked.add(line.strip())

    for probe in (derived[0], derived[len(derived) // 2], derived[-1]):
        if not check_ignored(probe):
            fails.append("derived package NOT ignored: " + probe)
        if probe in now_tracked:
            fails.append("derived package STILL TRACKED: " + probe)
    if not fails:
        print("  ok    first/middle/last derived: ignored AND untracked")

    for ctrl in CONTROLS_MUST_STAY_TRACKED + [MANIFEST]:
        if not os.path.exists(os.path.join(REPO, ctrl)):
            print("  note  control absent, skipped: " + ctrl)
            continue
        if check_ignored(ctrl):
            fails.append("CONTROL IS IGNORED, over-matched: " + ctrl)
        else:
            print("  ok    NOT ignored: " + ctrl)
    for ctrl in CONTROLS_MUST_STAY_TRACKED:
        rel_ok = git("ls-files", "--", ctrl).strip()
        if os.path.exists(os.path.join(REPO, ctrl)) and not rel_ok:
            fails.append("CONTROL LOST FROM THE INDEX: " + ctrl)

    survivors = sorted(now_tracked)[:3]
    bad = [r for r in survivors if check_ignored(r)]
    if bad:
        fails.append("a still-tracked actor is now ignored: " + bad[0])
    elif survivors:
        print("  ok    %d sampled surviving tracked actors: not ignored"
              % len(survivors))
    print("  info  %d packages remain tracked under %s (the real actors)"
          % (len(now_tracked), EXT_ACTORS))

    left = [ln for ln in git("status", "--porcelain", "--", EXT_ACTORS
                             ).splitlines() if ln.startswith("??")]
    if left:
        fails.append("%d untracked files still visible under %s"
                     % (len(left), EXT_ACTORS))
    else:
        print("  ok    no untracked files remain under " + EXT_ACTORS)

    print("")
    if fails:
        for f in fails:
            print("FAIL  " + f)
        return 1
    print("ALL CHECKS PASSED -- %d HLOD packages (%s) listed; the ignore "
          "match was VERIFIED on first/middle/last (not all N); controls "
          "tracked" % (len(derived), human(total)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
